### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by vishaal27** [ZrrSkywalker/CaFo#1]
Hi, are there any plans to release the paper on arxiv? If not, please let me know what the best way to cite your work would be by providing a bibtex entry. Thanks!

**Comment by ZrrSkywalker** [comment]
Thanks for your interest in our work. We are about to release the paper on arXiv and will reach you once we get the bibtex entry. Thanks!

**Comment by ZrrSkywalker** [comment]
Thanks for waiting @vishaal27. Our bibtex is below:
@article{zhang2023prompt,
  title={Prompt, Generate, then Cache: Cascade of Foundation Models makes Strong Few-shot Learners},
  author={Renrui Zhang, Xiangfei Hu, Bohao Li, Siyuan Huang, Hanqiu Deng, Hongsheng Li, Yu Qiao, Peng Gao},
  journal={arXiv preprint arXiv:2303.02151},
  year={2023}
}
